aula/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
     # URLs controle
    # url(r'^controleaula$', views.controle_aula_list, name='controle_aula_list'),
    url(r'^controleaula/create/(?P<aulaid>\d+)/(?P<pacienteid>\d+)$', views.controle_aula_create, name='controle_aula_create'),
    url(r'^controleaula/update/(?P<aulaid>\d+)/(?P<pacienteid>\d+)$', views.controle_aula_update, name='controle_aula_update'),
    url(r'^controleaula/delete/(?P<pk>\d+)$', views.controle_aula_delete, name='controle_aula_delete'),
    url(r'^controleaula/dashboard/(?P<pk>\d+)$', views.controle_aula_dashboard, name='controle_aula_dashboard'),
    url(r'^controleaula/import/update/(?P<pk>\d+)$', views.import_controleaula_update, name='import_controleaula_update'),
    
     # URLs aula
    url(r'^aula$', views.aula_list, name='aula_list'),
    url(r'^aula/create/$', views.aula_create, name='aula_create'),
    url(r'^aula/update/(?P<pk>\d+)$', views.aula_update, name='aula_update'),
    url(r'^aula/delete/(?P<pk>\d+)$', views.aula_delete, name='aula_delete'),
    url(r'^aula/alunos/(?P<pk>\d+)$', views.aula_alunos, name='aula_alunos'),
    url(r'^aula/controle/(?P<pk>\d+)$', views.paciente_controle_aula, name='paciente_controle_aula'),
    
    url(r'^planilha$', views.adicao_planilha, name='adicao_planilha'),
]

servicos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from servicos import views

urlpatterns = [

    # URLs CLIENTE SERVICO
    url(r'^cliente_servico$', views.cliente_servico_list, name='cliente_servico_list'),
    url(r'^cliente_servico/create/$', views.cliente_servico_create, name='cliente_servico_create'),
    url(r'^cliente_servico/update/(?P<pk>\d+)$', views.cliente_servico_update, name='cliente_servico_update'),
    url(r'^cliente_servico/delete/(?P<pk>\d+)$', views.cliente_servico_delete, name='cliente_servico_delete'),
    
    
        # URLs LAUDO PRE PARTICIPCAO    
    url(r'^laudo_preparticipacao/(?P<pk>\d+)$', views.laudo_preparticipacao_listar, name='laudo_preparticipacao_listar'),
    url(r'^laudo_preparticipacao/create/$', views.laudo_preparticipacao_criar, name='laudo_preparticipacao_criar'),
    url(r'^laudo_preparticipacao/update/(?P<pk>\d+)$', views.laudo_preparticipacao_atualizar, name='laudo_preparticipacao_atualizar'),
    url(r'^laudo_preparticipacao/delete/(?P<pk>\d+)$', views.laudo_preparticipacao_excluir, name='laudo_preparticipacao_excluir'),
    url(r'^laudo_preparticipacao/print/(?P<pk>\d+)$', views.laudo_preparticipacao_print, name='laudo_preparticipacao_print'),
    
]

cadastro/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from decimal import Decimal
from datetime import date

class ParametrosGerencial(models.Model):
    
    dias_aviso_contrato = models.IntegerField(blank=True, null=True)
    dias_aviso_avaliacao_fisica = models.IntegerField(blank=True, null=True)
    dias_aviso_avaliacao_clinica = models.IntegerField(blank=True, null=True)
    dias_aviso_exames = models.IntegerField(blank=True, null=True)
    dias_aviso_falta = models.IntegerField(blank=True, null=True)
    tamanho_volta_teste_caminhada = models.DecimalField(max_digits=5, decimal_places=2,null=True,blank=True, default=Decimal('0.00'))


class Plano(models.Model):

    nome = models.CharField(max_length=200, unique=True, error_messages={'unique':"Já existe um Plano com este nome cadastrado."})

    frequencia = models.IntegerField("Frequência",blank=True, null=True)
    periodo_total = models.IntegerField("Período total")
    suspensao = models.IntegerField("Suspensão de até")
    periodo_avaliacao_fisica = models.IntegerField("Av. Física(Periodicidade)")
    periodo_avaliacao_clinica = models.IntegerField("Av. Clínica(Periodicidade)")
    
    def __str__(self):
        return self.nome


class Empresa(models.Model):

    nome = models.CharField(max_length=200, unique=True, error_messages={'unique':"Já existe uma Empresa com este nome cadastrado."})
    
    def __str__(self):
        return self.nome


class Hospital(models.Model):

    nome = models.CharField(max_length=200, unique=True, error_messages={'unique':"Já existe um Hospital com este nome cadastrado."})
    
    def __str__(self):
        return self.nome


class ConvenioMedico(models.Model):

    nome = models.CharField(max_length=200, unique=True, error_messages={'unique':"Já existe um Convênio com este nome cadastrado."})
    
    def __str__(self):
        return self.nome


class MedicoAssistente(models.Model):
    
    nome = models.CharField(max_length=200, unique=True, error_messages={'unique':"Já existe um Médico com este nome cadastrado."})
    telefone = models.CharField(max_length=200)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ('nome',)


class Professor(models.Model):
    
    nome = models.CharField(max_length=200)
    telefone = models.CharField(max_length=200)
    email = models.EmailField(blank=True)
    
    def __str__(self):
        return self.nome

    class Meta:
        ordering = ('nome',)
    

class Paciente(models.Model):

    nome = models.CharField(max_length=200)
    telefone = models.CharField(max_length=200)
    data_nascimento = models.DateTimeField(blank=True, null=True)
    cpf = models.CharField(max_length=20)
    rg = models.CharField(max_length=20,blank=True, null=True)
    plano = models.ManyToManyField(Plano, blank=True)
    hospital = models.ManyToManyField(Hospital, blank=True)
    telefone_emergencia = models.CharField(max_length=200)
    convenio_medico = models.ManyToManyField(ConvenioMedico)
    medico_assistente = models.ManyToManyField(MedicoAssistente)
    
    matricula = models.CharField(max_length=20, blank=True, null=True)
    #data_vencimento = models.DateTimeField(blank=True, null=True)
    data_inicial_contrato = models.DateTimeField(blank=True, null=True)
    data_final_contrato = models.DateTimeField(blank=True, null=True)
    
    OPCAO_RACIAL = (
        ('ASIATICO', 'Asiatico'),
        ('BRANCO', 'Branco'),
        ('AFROAMERICANO', 'Afro-Americano'),
    )
    
    raca = models.CharField(max_length=70, choices=OPCAO_RACIAL)
    
    OPCAO_SEXO = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    
    sexo = models.CharField(max_length=25, choices=OPCAO_SEXO)
    
    ativo = models.BooleanField(default=True)
    prospect = models.BooleanField(default=True)
    cliente_servico = models.BooleanField("Cliente de serviços", default=False)
    
    def __str__(self):
        return self.nome
    
    def idade(self):
        today = date.today()
        return today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))

    class Meta:
        ordering = ['nome']

servicos/models.py
# -*- coding: utf-8 -*-
from django.db import models
from cadastro.models import Paciente
from django.conf import settings


# Create your models here.
class LaudoPreParticipacao(models.Model):
    
    paciente = models.ForeignKey(Paciente)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Responsável", null=True, blank=True)
    data_criacao = models.DateField("Data do laudo", null=True, blank=True)
    
    objetivo = models.CharField(max_length=1500, null=True, blank=True)
    texto_avaliacao_clinica = models.CharField("Descrição Avaliação Clínica", max_length=4000, null=True, blank=True)
    texto_avaliacao_fisica = models.CharField("Descrição Avaliação Física", max_length=4000, null=True, blank=True)
    texto_avaliacao_nutricional = models.CharField("Descrição Avaliação Nutricional", max_length=4000, null=True, blank=True)

servicos/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from cadastro.models import Paciente


class ClienteServicoForm(ModelForm):
    
    class Meta:
        model = Paciente
        fields = ['nome', 'telefone', 'data_nascimento', 'cpf', 'cliente_servico', 'sexo']
        widgets = {
            'cliente_servico': forms.HiddenInput(),
            'data_nascimento': forms.TextInput(attrs={'type': 'date', 'class': 'form-control textinput textInput'}),
        }



class LaudoPreParticipacaoForm(ModelForm):
    
    class Meta:
        model = LaudoPreParticipacao
        fields = '__all__'
        widgets = {
            'usuario': forms.HiddenInput(),
            'objetivo': forms.Textarea(),
            'texto_avaliacao_clinica': forms.Textarea(),
            'texto_avaliacao_fisica': forms.Textarea(),
            'texto_avaliacao_nutricional': forms.Textarea(),
            'data_criacao': forms.TextInput(attrs={'type': 'date'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(LaudoPreParticipacaoForm, self).__init__(*args, **kwargs)
        self.fields['paciente'].queryset = Paciente.objects.filter(cliente_servico=True)

servicos/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from cadastro.models import Paciente
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse, request
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from datetime import datetime
from easy_pdf.rendering import render_to_pdf_response



"""
     VIEWS PARA CLIENTES
"""
@login_required
def cliente_servico_list(request, template_name='servicos/cliente_servico/lista_cliente_servico.html'):

    """ Lista das solucoes ja cadastradas ao problema """
    cliente_servicos = Paciente.objects.filter(cliente_servico=True)
    
    return render(request, template_name, {'cliente_servicos' : cliente_servicos, 'menu-cliente-servico' : 'active'})


@login_required
def cliente_servico_delete(request, pk):
    cliente_servico = get_object_or_404(Paciente, pk=pk)
    data = dict()
    if request.method == 'POST':
        cliente_servico.delete()
        data['form_is_valid'] = True
        cliente_servicos = Paciente.objects.filter(cliente_servico=True)
        data['html_cliente_servico_list'] = render_to_string('servicos/cliente_servico/lista_cliente_servico_parcial.html', {
            'cliente_servicos': cliente_servicos
        })
    else:
        context = {'cliente_servico': cliente_servico}
        data['html_form'] = render_to_string('servicos/cliente_servico/cliente_servico_confirma_delete.html', context, request=request)
    return JsonResponse(data)


@login_required
def save_cliente_servico_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            cliente_servicos = Paciente.objects.all()
            data['html_paciente_list'] = render_to_string('paciente/lista_paciente_parcial.html', {
                'pacientes': cliente_servicos
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@login_required
def cliente_servico_create(request):
    if request.method == 'POST':
        form = ClienteServicoForm(request.POST)
    else:
        form = ClienteServicoForm(initial={'cliente_servico': 'True'})
    return save_cliente_servico_form(request, form, 'servicos/cliente_servico/cria_cliente_servico_modal.html')


@login_required
def cliente_servico_update(request, pk):
    cliente_servico = get_object_or_404(Paciente, pk=pk)
    if request.method == 'POST':
        form = ClienteServicoForm(request.POST, instance=cliente_servico)
    else:
        form = ClienteServicoForm(instance=cliente_servico)
    return save_cliente_servico_form(request, form, 'servicos/cliente_servico/atualiza_cliente_servico_modal.html')






"""

   VIEWS PARA LAUDO DE PRE PARTICIPACAO
   
"""


@login_required
def laudo_preparticipacao_criar(request, template_name='servicos/laudo_preparticipacao/laudo_preparticipacao_criar.html'):

    if request.method == "POST":
        form = LaudoPreParticipacaoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('laudo_preparticipacao_listar', pk=form.instance.paciente.pk)
    else:
        form = LaudoPreParticipacaoForm(initial={'usuario': request.user})

    return render(request, template_name, {'form': form, 'menu_laudo_preparticipacao': 'active'})


@login_required
def laudo_preparticipacao_listar(request, pk, template_name='servicos/laudo_preparticipacao/laudo_preparticipacao_lista.html'):

    paciente = get_object_or_404(Paciente, pk=pk)
    laudos = LaudoPreParticipacao.objects.filter(paciente=paciente)

    data = {}

    data['laudos'] = laudos
    data['menu_laudo_preparticipacao'] = 'active'

    return render(request, template_name, data)


@login_required
def laudo_preparticipacao_atualizar(request, pk, template_name='servicos/laudo_preparticipacao/laudo_preparticipacao_atualizar.html'):

    laudo = get_object_or_404(LaudoPreParticipacao, pk=pk)

    if request.method == 'POST':
        form = LaudoPreParticipacaoForm(request.POST, instance=laudo)
        if form.is_valid():
            form.save()
            return redirect('laudo_preparticipacao_listar', pk=form.instance.paciente.pk)
    else:
        form = LaudoPreParticipacaoForm(instance=laudo)

    return render(request, template_name, {'form': form, 'menu_laudo_preparticipacao': 'active'})


@login_required
def laudo_preparticipacao_excluir(request, pk):

    laudo_preparticipacao = get_object_or_404(LaudoPreParticipacao, pk=pk)

    data = dict()

    if request.method == 'POST':
        laudo_preparticipacao.delete()
        data['form_is_valid'] = True
        laudos = LaudoPreParticipacao.objects.filter(paciente=laudo_preparticipacao.paciente)
        data['html_laudo_preparticipacao_list'] = render_to_string('servicos/laudo_preparticipacao/laudo_preparticipacao_lista_parcial.html', {
            'laudos': laudos
        })
    else:
        context = {'laudo': laudo_preparticipacao, 'menu_laudo_preparticipacao': 'active'}
        data['html_form'] = render_to_string('servicos/laudo_preparticipacao/laudo_preparticipacao_confirma_delete.html', context,
                                             request=request)
    return JsonResponse(data)


def laudo_preparticipacao_print(request, pk):

    laudo = get_object_or_404(LaudoPreParticipacao, pk=pk)
    paciente = laudo.paciente
    laudo_form = LaudoPreParticipacaoForm(instance=laudo)

    data = {
        'paciente': paciente,
        'laudo': laudo_form,
    }

    return render_to_pdf_response(request, 'servicos/laudo_preparticipacao/laudo_preparticipacao_print.html', data)
    #return render(request, 'servicos/laudo_preparticipacao/laudo_preparticipacao_print.html', data)

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_atualizar.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}

{{ form.css }}

<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor">Editar Laudo</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item active">Editar Laudo</li>
        </ol>
    </div>
</div>


<div class="row">
    <div class="col-xl-8 offset-xl-2">
        <div class="card mb-3">
            <div class="card-body">
                <h2 class="page-header">Editar Laudo de Pré-Participação</h2>
                <hr>
                <form method="post" action="{% url 'laudo_preparticipacao_atualizar' form.instance.pk %}">
                    {% csrf_token %}

                    {% include 'servicos/laudo_preparticipacao/laudo_preparticipacao_form.html' %}

                    <a type="button" class="btn btn-default"
                       href="{% url 'laudo_preparticipacao_listar' form.instance.pk %}">Cancelar</a>
                    <button type="submit" class="btn btn-primary">Salvar</button>

                </form>
            </div>
        </div>
    </div>
</div>

{{ form.js }}

{% endblock content %}

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_confirma_delete.html
<form method="post" action="{% url 'laudo_preparticipacao_excluir' laudo.id %}" class="js-laudo-preparticipacao-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Deletar Laudo Pré Participação</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Tem certeza que deseja deletar o laudo <strong>{{ laudo.id }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-danger">Deletar</button>
  </div>
</form>

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_criar.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}

{{ form.css }}

<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor">Criar Laudo</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item active">Criar Laudo</li>
        </ol>
    </div>
    <!--<div class="col-md-7 col-4 align-self-center">-->
    <!--    <div class="d-flex m-t-10 justify-content-end">-->

    <!--        <div class="">-->
    <!--            <a href="{% url 'laudo_preparticipacao_criar' %}">-->
    <!--            <button type="button" class="btn btn-primary">-->
    <!--              <span class="mdi text-white mdi-plus"></span>-->
    <!--              Novo-->
    <!--            </button>-->
    <!--            </a>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--</div>-->
</div>


<div class="row">
    <div class="col-xl-8 offset-xl-2">
        <div class="card mb-3">
            <div class="card-body">
                <h2 class="card-title">Novo Laudo</h2>
                <hr>
                <div class="mt-40">
                    <form method="post" action="{% url 'laudo_preparticipacao_criar'  %}">
                        {% csrf_token %}

                        {% include 'servicos/laudo_preparticipacao/laudo_preparticipacao_form.html' %}

                        <button type="submit" class="btn btn-primary" onclick="this.disabled=true,this.form.submit();">
                            Salvar
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{{ form.js }}

{% endblock content %}

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_form.html
{% load crispy_forms_tags %}
{% csrf_token %}
{{ form | crispy }}

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_lista.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}

{% block scripts %}
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/servicos/laudo-preparticipacao.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor">Lista de Laudos</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item active">Lista de Laudos</li>
        </ol>
    </div>
    <div class="col-md-7 col-4 align-self-center">
        <div class="d-flex m-t-10 justify-content-end">

            <div class="">
                <a href="{% url 'laudo_preparticipacao_criar' %}">
                <button type="button" class="btn btn-primary">
                  <span class="mdi text-white mdi-plus"></span>
                  Novo
                </button>
                </a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Laudos Emitidos</h4>
                <div class="table-responsive m-t-40">
                <table cellpadding="0" cellspacing="0" border="0" id="laudo-preparticipacao-table" class="display nowrap table table-hover table-striped table-bordered dataTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Data</th>
                            <th>Paciente</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'servicos/laudo_preparticipacao/laudo_preparticipacao_lista_parcial.html' %}
                    </tbody>
                </table>
                </div>
            </div>
        </div>
        
        <!-- MODAL -->
        <div class="modal fade" id="modal-laudo-preparticipacao">
            <div class="modal-dialog">
              <div class="modal-content">
        
              </div>
            </div>
          </div>


    </div>
</div>


{% endblock content %}

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_lista_parcial.html
{% for laudo in laudos %}
    <tr>
        <td>{{ laudo.id }}</td>
        <td>{{ laudo.data_criacao|date:"SHORT_DATE_FORMAT" }}</td>
        <td>{{ laudo.paciente }}</td>
        <td>
            <a class='btn btn-warning btn-sm m-1' href="{% url 'laudo_preparticipacao_atualizar' laudo.id %}"> <span class="fa fa-edit"></span> Editar</a>
            <button class='btn btn-danger btn-sm js-delete-laudo-preparticipacao m-1' data-url="{% url 'laudo_preparticipacao_excluir' laudo.id %}"> <span class="fa fa-trash"></span> Excluir</button>
            <a class='btn btn-primary btn-sm m-1' href="{% url 'laudo_preparticipacao_print' laudo.id %}"> <span class="fa fa-print"></span> Imprimir</a>
        </td>
    </tr>
{% endfor %}

templates/servicos/laudo_preparticipacao/laudo_preparticipacao_print.html
{% extends "easy_pdf/base.html" %}

{% load static %}

{% block layout_style %}
    <style type="text/css">
        @page {
            size: "A4";
            margin-left: 2.5cm;
            margin-right: 2.5cm;
            margin-top: 4cm;
            margin-bottom: 2.5cm;
            @frame header {
                -pdf-frame-content: page-header;
                margin-top: 1cm;
                margin-right: 2mm;
                margin-bottom: 2cm;
                margin-left: 1.2cm;
            }
            @frame footer_frame {           /* Static frame */
                -pdf-frame-content: footer_content;
                bottom: 0.3cm;
                margin-left: 1cm;
                margin-right: 1cm;
                height: 2cm;
            }
        }
    </style>
{% endblock %}

{% block extra_style %}
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <style type="text/css">
        html {
            font-family: "Helvetica", "sans-serif";
            color: #333333;
        }
        p {
            margin: 0 0 0 0;
            font-size: 11pt;
            padding: 0;
        }
        .text-left { text-align: left; }
        .text-right { text-align: right; }
        .bottom-10 { margin-bottom: 10px; }
        .bottom-20 { margin-bottom: 20px; }
        .header { color: #7f7f7f; }
        .header p { font-size: 13px; line-height: 1.5em; }
        .header-link { font-weight: bold; text-decoration: none; color: #4F81BD; font-size: 14px; }
        .logo { margin-bottom: 60px; margin-left: -25px; }
        .logo img { zoom: 50%; }
        .recipient { margin-left: 7cm; }
        .main h1 {
            margin: 18px 0 18px 0;
            font-size: 250%;
            font-weight: normal;
            color: #4F81BD;
            text-align: center;
        }
        .main h2 {
            margin: 18px 0 6px 0;
            font-size: 180%;
            font-weight: normal;
            padding: 0;
        }

        .main h4 {
            margin: 18px 0 6px 0;
            font-size: 150%;
            font-weight: bold;
            padding: 0;
        }
        .info { border: 1px solid #4F81BD; padding: 10px; margin-top: 50px; margin-bottom: 50px; }
        .info a { color: #4F81BD; text-decoration: none; }
        #footer_content{
            text-align: center;
         }
        .texto-rodape{
            font-size: 11pt;
            color: #f9b564;
        }
        .texto-justificado{
            text-align: justify;
            text-justify: inter-word;
        }
        .subtitulo {
            font-weight: 1200;
            border-bottom: 1px;
        }
        .valor{
            word-wrap: break-word;
            word-break: break-all;
            overflow: hidden;
        }
        .texto-colunas{
            font-size: 11pt;
        }
    </style>
{% endblock %}

{%block page_header%}
    <div id="page-header">
        <div class="header">
            <p class="logo"><img src="{% static 'images/logo.jpeg' %}" /></p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="footer_content">
        <table>
            <tbody>
                <tr>
                    <td class="text-center">
                        <span class="texto-rodape">(27) 3019-0076</span>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <span class="texto-rodape">contato@institutohabilitar.com</span>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <span class="texto-rodape">Avenida Saturnino Rangel Mauro 454 - Jardim da Penha</span>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <span class="texto-rodape">Vitória ES - CEP 29060-770</span>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    <div id="content">
        <div class="main">
            <h1 style="font-weight: 800;">Avaliação Pré-Participação</h1>
            <br>
            <hr>
            <table>
                <tbody>
                    <tr style="padding-top: 10px">
                        <td class="text-center">
                            <h2><strong>Paciente:</strong> {{ paciente.nome }}</h2>
                        </td>
                    </tr>
                    <tr style="padding-top: 10px">
                        <td>
                            <h2><strong>Data:</strong> {{ laudo.data_criacao.value|date:"d/m/Y" }}</h2>
                        </td>
                        <td class="text-center">
                            <h2><strong >Idade:</strong> {{ paciente.idade }}</h2>
                        </td>
                        <td class="text-center">
                            <h2><strong>Sexo:</strong> {{ paciente.get_sexo_display }}</h2>
                        </td>
                    </tr>
                </tbody>
            </table>
            <hr>

            <br>
            <br>
            <div id="laudo-preparticipacao" >
                {% for field in laudo %}
                    {% if forloop.counter > 3 %}
                    {% if field.value != None %}
                        <h4>{{ field.label }}:</h4>
                        <div >
                            <p class="texto-justificado">
                                {{ field.value }}.
                            </p>
                        </div>
                    {% endif %}
                    {% endif %}
                {% endfor %}

            </div>

        </div>
    </div>
{% endblock %}